### ISSUE TITLE
Introduce a notes field for each entry

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/tpv-shared-database#23]
Just putting this out there for discussion, but I'm thinking that perhaps it would be really useful to have the basis on which the `cores`, `mem`, `gpu` values in the shared database were determined, whenever possible. For example, the basis could be something like: "Tested on an input size of 100GB and did not require more than 3GB of ram. Does not scale with increased CPUs". Just having some notes would allow an admin to determine whether the resource allocation is a potential problem. For example, perhaps a newer version of that tool does support multiple cores. Right now, we have no way to know whether some values are just guesses, or hard constraints (e.g. Not a multi-core tool).

Another thing we could do is to query the usegalaxy.* databases, and find the largest input sizes that the tool has successfully run against, actual max ram and cores used, and maybe include those in the notes for reference?

The notes could also be a more formalized structure like:
```yaml
resources:
 -  date: 4th May 2023
    max_input_tested: 100GB
    max_cores_logged: 1
    max_ram_logged: 24GB
    source: usegalaxy.eu
    notes: tool is not a multicore tool as of v0.1
```

Would this be useful or mostly just noise? Alternatively, it could live in a separate file.
