### ISSUE TITLE
Add rule for ```recetox_aplcms_compute_clusters``` to scale memory according to the input.

### ISSUE THREAD

**Issue by hechth** [galaxyproject/tpv-shared-database#74]
The tool currently has no config (so I assume 4GB by default?) and crashes when being given about 1GB of input data.

So I assume a rule like this would make sense?

```
  toolshed.g2.bx.psu.edu/repos/recetox/recetox_aplcms_compute_clusters/recetox_aplcms_compute_clusters/.*:
    mem: 4
    rules:
    - id: rcx_aplcms_clusters_large_input
      if: input_size >= 0.8
      mem: 8
```

Is it also possible to stack these rules, so to provide even more memory if the input is even bigger?
